Finished Chapter 1 Of RoughStory
ArvickC/CakeCraft-RPG pull request #23
Opened 2020-09-08 01:09 UTC by ArvickC

Chapter 1 Complete
Version Updated
Added golden apple to Info.yml

2020-09-08 02:24 UTC, WinstonLuo07 commented on RoughStory.md
> +On your way home you find a person with a golden apple, he offers it to you... (Help me add more here, idk what to add)
what is the purpose of this golden apple

2020-09-08 02:26 UTC, WinstonLuo07 commented on RoughStory.md
> +You take the golden apple and eat it, you start to walk home again but feel light headed, everything starts to go black, and you start toppling. You hear footsteps and turn to see what they are. You
please rework this, this has no explanation

2020-09-08 02:26 UTC, ArvickC commented on RoughStory.md
> +On your way home you find a person with a golden apple, he offers it to you... (Help me add more here, idk what to add)
Just to lead into chapter 2, as you see further into the story if you accept the apple; you get poisoned and run into the shack with the book. Then we start chapter 2.

2020-09-08 02:33 UTC, WinstonLuo07 commented on RoughStory.md
> +You decline the golden apple offer and walk home.
I feel like we should only have 1 path from the beginning because it will be more simple to code and understand.

2020-09-08 02:33 UTC, WinstonLuo07 commented on Info.yml
> +                    - Shadyish guy (with purple eyes) [mind controlled] that gives you a golden apple! (Poison and you fall on way back)
don't like this because there is 2 story paths

2020-09-08 02:33 UTC, ArvickC commented on RoughStory.md
> +You decline the golden apple offer and walk home.
We don't have to code anything for this part...

2020-09-08 02:34 UTC, ArvickC commented on RoughStory.md
> +You take the golden apple and eat it, you start to walk home again but feel light headed, everything starts to go black, and you start toppling. You hear footsteps and turn to see what they are. You
Explain?

2020-09-08 02:34 UTC, ArvickC commented on Info.yml
> +                    - Shadyish guy (with purple eyes) [mind controlled] that gives you a golden apple! (Poison and you fall on way back)
Explain?

2020-09-08 02:34 UTC, WinstonLuo07 requested changes
i don't think we should have a 2nd story, if you require one please change the story

2020-09-08 02:38 UTC, WinstonLuo07 commented on RoughStory.md
> +You decline the golden apple offer and walk home.
Then how do you suggest we close off one story while doing the other story

2020-09-08 02:38 UTC, ArvickC commented on RoughStory.md
> +You decline the golden apple offer and walk home.
huh?

2020-10-01 17:39 UTC, WinstonLuo07 commented on Info.yml
> +                    - Shadyish guy (with purple eyes) [mind controlled] Follows You! (Going back from Village)
I like this new guy

2020-10-01 17:41 UTC, WinstonLuo07 approved these changes
Nice job.

2020-10-01 17:42 UTC, merged